//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSConn : DbContext
    {
        public HRMSConn()
            : base("name=HRMSConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAttendanceMaster> tblAttendanceMasters { get; set; }
        public virtual DbSet<tblCommonContact> tblCommonContacts { get; set; }
        public virtual DbSet<tblDepartmentMaster> tblDepartmentMasters { get; set; }
        public virtual DbSet<tblDesignationMaster> tblDesignationMasters { get; set; }
        public virtual DbSet<tblLeaveApplicationTrack> tblLeaveApplicationTracks { get; set; }
        public virtual DbSet<tblLeaveBalance> tblLeaveBalances { get; set; }
        public virtual DbSet<tblLeaveMaster> tblLeaveMasters { get; set; }
        public virtual DbSet<tblMenuMaster> tblMenuMasters { get; set; }
        public virtual DbSet<tblMenuRelatedAction> tblMenuRelatedActions { get; set; }
        public virtual DbSet<tblMonthySal> tblMonthySals { get; set; }
        public virtual DbSet<tblNoticeMaster> tblNoticeMasters { get; set; }
        public virtual DbSet<tblPermissionMaster> tblPermissionMasters { get; set; }
        public virtual DbSet<tblPolicyMaster> tblPolicyMasters { get; set; }
        public virtual DbSet<tblProjectAllotted> tblProjectAllotteds { get; set; }
        public virtual DbSet<tblProjectMaster> tblProjectMasters { get; set; }
        public virtual DbSet<tblSalaryMaster> tblSalaryMasters { get; set; }
        public virtual DbSet<tblSupportAdminManager> tblSupportAdminManagers { get; set; }
        public virtual DbSet<tblSupportTickedMaster> tblSupportTickedMasters { get; set; }
        public virtual DbSet<tblTaskMaster> tblTaskMasters { get; set; }
        public virtual DbSet<tblTeamMaster> tblTeamMasters { get; set; }
        public virtual DbSet<tblTicketRef> tblTicketRefs { get; set; }
        public virtual DbSet<tblTimeSheetManager> tblTimeSheetManagers { get; set; }
        public virtual DbSet<tblUserMaster> tblUserMasters { get; set; }
        public virtual DbSet<tblSettingsMaster> tblSettingsMasters { get; set; }
        public virtual DbSet<tblCommonDoc> tblCommonDocs { get; set; }
    }
}
