//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommonDoc
    {
        public int DocId { get; set; }
        public string DocName { get; set; }
        public string DocFileName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
