//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDesignationMaster
    {
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public Nullable<int> RefDepartmentId { get; set; }
    
        public virtual tblDepartmentMaster tblDepartmentMaster { get; set; }
    }
}
