//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveApplicationTrack
    {
        public int BLId { get; set; }
        public Nullable<int> refEuid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> NoOfDays { get; set; }
        public string ApplicantNotes { get; set; }
        public string ApprovedNotes { get; set; }
        public Nullable<bool> ApproveStatus { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
