//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermissionMaster
    {
        public int PermissionId { get; set; }
        public Nullable<int> refUserId { get; set; }
        public Nullable<int> refMenuId { get; set; }
        public Nullable<int> refMenuParentID { get; set; }
        public Nullable<bool> Allowed { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
