//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProjectMaster()
        {
            this.tblProjectAllotteds = new HashSet<tblProjectAllotted>();
        }
    
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EstEndDate { get; set; }
        public Nullable<System.DateTime> ActEndDate { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectNotes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Createdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectAllotted> tblProjectAllotteds { get; set; }
    }
}
