//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryMaster
    {
        public int SId { get; set; }
        public Nullable<int> refEID { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> HRA { get; set; }
        public Nullable<int> SpecialAllowance { get; set; }
        public Nullable<int> ConveyanceAllowance { get; set; }
        public Nullable<int> MealAllowance { get; set; }
        public Nullable<int> TelephoneAllowance { get; set; }
        public Nullable<int> OtherAllowance { get; set; }
        public string OtherAllowanceNotes { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<int> IncomeTax { get; set; }
        public Nullable<int> OtherDeduction { get; set; }
        public string OtherDeductionNotes { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
