//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupportTickedMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupportTickedMaster()
        {
            this.tblTicketRefs = new HashSet<tblTicketRef>();
        }
    
        public int Tid { get; set; }
        public string TSubject { get; set; }
        public Nullable<int> TDeptid { get; set; }
        public string TStatus { get; set; }
        public Nullable<int> UserInvolved { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicketRef> tblTicketRefs { get; set; }
    }
}
