//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettingsMaster
    {
        public int Cid { get; set; }
        public string CompanyNameSal { get; set; }
        public string CompanyShortName { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyInstructionForSal { get; set; }
        public string AddressContactDetails { get; set; }
    }
}
