//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskMaster
    {
        public int TaskId { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> AssignBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Details { get; set; }
        public string FinishNotes { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
