//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSheetManager
    {
        public int TimeId { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<decimal> TimeHours { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> refTimeEmpId { get; set; }
        public Nullable<int> refTimeProjectId { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
