//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamMaster
    {
        public int TeamId { get; set; }
        public Nullable<int> TeamUsers { get; set; }
        public Nullable<int> TeamParentUser { get; set; }
    
        public virtual tblUserMaster tblUserMaster { get; set; }
    }
}
