//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserMaster()
        {
            this.tblAttendanceMasters = new HashSet<tblAttendanceMaster>();
            this.tblLeaveApplicationTracks = new HashSet<tblLeaveApplicationTrack>();
            this.tblLeaveBalances = new HashSet<tblLeaveBalance>();
            this.tblMonthySals = new HashSet<tblMonthySal>();
            this.tblPermissionMasters = new HashSet<tblPermissionMaster>();
            this.tblSalaryMasters = new HashSet<tblSalaryMaster>();
            this.tblSupportAdminManagers = new HashSet<tblSupportAdminManager>();
            this.tblSupportTickedMasters = new HashSet<tblSupportTickedMaster>();
            this.tblTaskMasters = new HashSet<tblTaskMaster>();
            this.tblTeamMasters = new HashSet<tblTeamMaster>();
            this.tblTimeSheetManagers = new HashSet<tblTimeSheetManager>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ImagePath { get; set; }
        public string HighestQualification { get; set; }
        public string SecondHighestQualification { get; set; }
        public string OtherDetails { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string EmpId { get; set; }
        public Nullable<bool> IsWebMaster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceMaster> tblAttendanceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplicationTrack> tblLeaveApplicationTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveBalance> tblLeaveBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMonthySal> tblMonthySals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermissionMaster> tblPermissionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalaryMaster> tblSalaryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupportAdminManager> tblSupportAdminManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupportTickedMaster> tblSupportTickedMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskMaster> tblTaskMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamMaster> tblTeamMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTimeSheetManager> tblTimeSheetManagers { get; set; }
    }
}
